version: "3.8"  # Use an appropriate Docker Compose version

services:
  app:
    container_name: "sf-ocr"
    build:
      context: .
      dockerfile: Dockerfile  # Specify your Dockerfile name if not using the default "Dockerfile"
    command: uvicorn src.main:app --host 0.0.0.0 --port 5000  # Adjust the command to match your FastAPI application setup
    stdin_open: true
    tty: true
    ports:
      - 5000:5000

